name: main
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@4e8ff5adddafdfd8c933664d2c0f72dcfaacc0bc
      - run: npm t
